#Wine quality Prediction


##Importing the Libraries and Dataset

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
data=pd.read_csv("WineDataset.csv")
x=data.iloc[:,0:13].values
y=data.iloc[:,-1].values

In [21]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


##Checking the presence of Null values

In [22]:
data.isnull().sum()

Alcohol                         0
Malic Acid                      0
Ash                             0
Alcalinity of ash               0
Magnesium                       0
Total phenols                   0
Flavanoids                      0
Nonflavanoid phenols            0
Proanthocyanins                 0
Color intensity                 0
Hue                             0
OD280/OD315 of diluted wines    0
Proline                         0
Wine                            0
dtype: int64

##Spliting the Train and Test data

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

##Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [27]:
print(x_train)

[[ 0.88  0.8   0.64 ...  0.03 -1.06 -0.21]
 [-0.37 -0.76 -0.4  ...  0.03 -0.73 -0.82]
 [-1.7  -0.34 -0.32 ...  0.9   0.52 -1.31]
 ...
 [-0.7  -0.69 -0.66 ...  0.47  0.52 -1.31]
 [ 1.14 -0.62 -0.92 ... -0.19  1.03  0.8 ]
 [ 1.46  0.12  0.42 ... -1.46 -1.22 -0.27]]


In [28]:
print(y_train)

[3 2 2 3 1 1 2 2 2 1 3 2 3 1 3 3 1 3 1 2 3 3 2 3 3 1 2 3 2 2 3 2 1 2 2 2 1
 1 2 2 3 3 2 2 2 3 3 1 3 2 2 2 2 2 1 1 2 1 3 1 3 1 1 2 1 2 2 1 3 2 1 2 2 2
 3 1 3 3 1 1 2 3 1 1 2 2 1 1 1 3 2 1 2 3 1 2 3 3 1 1 3 1 3 2 1 1 2 1 3 2 3
 1 3 3 3 1 2 2 2 2 3 3 2 2 1 2 3 3 1 1 3 2 2 2 1 1 1 2 2 2 1 3]


##Model Training

In [29]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

##Predicting the values

In [30]:
pred=model.predict(x_test)
print(pred)

[1.13 3.09 1.87 1.5  1.96 0.86 0.91 3.17 1.73 2.12 2.47 3.07 0.8  1.43
 2.89 1.89 1.08 0.52 2.51 0.85 1.48 1.42 1.59 1.7  2.23 2.07 1.75 2.2
 1.76 3.   0.93 1.24 2.21 1.27 1.04 1.3 ]


In [31]:
np.set_printoptions(precision=2)
print(np.concatenate((pred.reshape(len(pred),1),y_test.reshape(len(y_test),1)),1))

[[1.13 1.  ]
 [3.09 3.  ]
 [1.87 2.  ]
 [1.5  1.  ]
 [1.96 2.  ]
 [0.86 2.  ]
 [0.91 1.  ]
 [3.17 3.  ]
 [1.73 2.  ]
 [2.12 2.  ]
 [2.47 3.  ]
 [3.07 3.  ]
 [0.8  1.  ]
 [1.43 2.  ]
 [2.89 3.  ]
 [1.89 2.  ]
 [1.08 1.  ]
 [0.52 1.  ]
 [2.51 2.  ]
 [0.85 1.  ]
 [1.48 2.  ]
 [1.42 1.  ]
 [1.59 1.  ]
 [1.7  2.  ]
 [2.23 2.  ]
 [2.07 2.  ]
 [1.75 2.  ]
 [2.2  2.  ]
 [1.76 2.  ]
 [3.   3.  ]
 [0.93 1.  ]
 [1.24 1.  ]
 [2.21 2.  ]
 [1.27 1.  ]
 [1.04 1.  ]
 [1.3  1.  ]]


##Evaluation the Model

In [32]:
from sklearn.metrics import r2_score
r2_score(y_test, pred)

0.76437591539563