#House price prediction

##Importing libraries and datasets

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
data=pd.read_csv("hpdataset fin.csv")
x=data.iloc[:,0:15].values
y=data.iloc[:,-1].values

In [ ]:
print(x)

[[201 177 3 ... 6.8 0.9 'small']
 [196 182 4 ... 4.1 1.42 'medium']
 [198 182 4 ... 2.1 4.12 'medium']
 ...
 [153 147 3 ... 4.7 3.98 'extra_large']
 [180 158 2 ... 3.4 3.75 'large']
 [695 619 8 ... 0.4 4.64 'large']]


In [ ]:
print(y)

[165432 187043 148658 ... 106428 107579 537980]


##Checking null values and Printing values

In [ ]:
data.isnull().sum()

land_size_sqm                 0
house_size_sqm                0
no_of_rooms                   0
no_of_bathrooms               0
large_living_room             0
parking_space                 0
front_garden                  0
swimming_pool                 0
distance_to_school            0
wall_fence                    0
house_age                     0
water_front                   0
distance_to_supermarket_km    0
crime_rate_index              0
room_size                     0
property_value                0
dtype: int64

In [ ]:
print(data)

      land_size_sqm  house_size_sqm  no_of_rooms  no_of_bathrooms  \
0               201             177            3                1   
1               196             182            4                3   
2               198             182            4                4   
3               178             166            2                3   
4               183             165            3                1   
...             ...             ...          ...              ...   
4949            297             261            4                4   
4950            302             282            4                2   
4951            153             147            3                4   
4952            180             158            2                1   
4953            695             619            8                6   

     large_living_room parking_space front_garden swimming_pool  \
0                   No           Yes          Yes            No   
1                  Yes           Yes 

##Encoding the Catogorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
m=[4,5,6,7,9,11,14]
for i in range(0,7):
  x[:,m[i]]=l.fit_transform(x[:,m[i]])

In [ ]:
print(x)

[[201 177 3 ... 6.8 0.9 3]
 [196 182 4 ... 4.1 1.42 2]
 [198 182 4 ... 2.1 4.12 2]
 ...
 [153 147 3 ... 4.7 3.98 0]
 [180 158 2 ... 3.4 3.75 1]
 [695 619 8 ... 0.4 4.64 1]]


##Splitting the test and train data

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
print(x_train)

[[276 250 4 ... 3.4 2.58 1]
 [183 183 3 ... 6.6 4.33 1]
 [188 161 3 ... 5.5 2.55 0]
 ...
 [214 194 3 ... 3.1 5.42 2]
 [134 115 2 ... 5.5 5.88 1]
 [345 319 5 ... 4.3 3.38 2]]


In [ ]:
print(x_test)

[[343 322 5 ... 6.1 1.73 2]
 [216 187 4 ... 6.8 5.06 1]
 [295 272 4 ... 5.3 0.58 1]
 ...
 [260 257 4 ... 3.2 3.56 1]
 [170 162 2 ... 2.3 2.54 3]
 [270 259 4 ... 3.7 0.27 3]]


##Feature Scaling of independent varibles

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[ 0.25  0.2   0.14 ... -0.05 -0.25 -0.27]
 [-0.65 -0.51 -0.5  ...  1.56  0.76 -0.27]
 [-0.6  -0.74 -0.5  ...  1.01 -0.27 -1.34]
 ...
 [-0.35 -0.39 -0.5  ... -0.2   1.4   0.79]
 [-1.13 -1.23 -1.13 ...  1.01  1.66 -0.27]
 [ 0.92  0.93  0.77 ...  0.4   0.21  0.79]]


##Training linear regression model and Predicting price

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
pred=model.predict(x_test)
print(pred)

[262673.5  187498.12 266602.56 329747.28 142847.03  86428.87 166486.12
 256415.81 207589.78 233566.37 138582.74 209330.   230203.2  389342.66
 220180.18 202134.27 224601.27 281716.65 205964.68 156378.17 275317.72
 263105.53  80353.21  90936.96 322611.07 236989.18 220988.73 127550.25
 162241.65 132351.54 296326.81 375411.11 280092.39 474661.14 153474.
 335723.26 340764.84 107453.51 241184.   177482.66 183245.01 260164.14
 243047.23 246594.22 173729.06 295602.4  246534.02 101904.41 180198.17
 232798.47  69738.89 120896.78 149647.72 284196.14 113358.97 258432.55
 255587.35 118598.37 209832.6  224100.52 169103.58 156343.64 232560.36
 113772.51  95541.17 179912.8  292773.82 216129.47 172589.66 211995.8
 172341.97 127768.82 201920.01 414948.35 107280.37 128957.58 210160.75
 223016.82 262903.61  77925.95 226816.51  45467.81 164092.27 137830.27
 140700.47 267431.48 233169.81 301035.83 189163.78  79746.88 111208.11
 105996.02 246141.56 290775.07 225810.05 227581.66 264013.06 193684.36
 251217.4

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((pred.reshape(len(pred),1),y_test.reshape(len(y_test),1)),1))

[[262673.5  253516.  ]
 [187498.12 197211.  ]
 [266602.56 279870.  ]
 ...
 [189446.32 189921.  ]
 [132992.2  131699.  ]
 [251944.79 236517.  ]]


##Perfomance evaluation

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, pred)

0.9879397579611933